name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r book-rental-calculator/requirements.txt
        source book-rental-calculator/envs/dev
#       python book-rental-calculator/app.py
        
#     - name: Test with pytest
#       run: |
#         pip install pytest
#         pytest
